### ISSUE TITLE
Traceback with _parse_georss_point

### ISSUE THREAD

**Issue by iranzo** [kurtmckee/feedparser#181]
Hi,
I got this similar to #130 :

~~~
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> url='https://mundosauriga.blogspot.com/feeds/posts/default?alt=rss'
>>> import feedparser
>>> feed = feedparser.parse(url)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/feedparser.py", line 3766, in _gen_georss_coords
    t = [nxt(), nxt()][::swap and -1 or 1]
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/feedparser.py", line 3956, in parse
    saxparser.parse(source)
  File "/usr/lib64/python3.7/site-packages/drv_libxml2.py", line 239, in parse
    _d(reader.Name()))
  File "/usr/lib/python3.7/site-packages/feedparser.py", line 2052, in endElementNS
    self.unknown_endtag(localname)
  File "/usr/lib/python3.7/site-packages/feedparser.py", line 696, in unknown_endtag
    method()
  File "/usr/lib/python3.7/site-packages/feedparser.py", line 1463, in _end_georss_point
    geometry = _parse_georss_point(self.pop('geometry'))
  File "/usr/lib/python3.7/site-packages/feedparser.py", line 3775, in _parse_georss_point
    coords = list(_gen_georss_coords(value, swap, dims))
RuntimeError: generator raised StopIteration
~~~

Any hint for this?

Feedparser version is provided by  `python3-feedparser-5.2.1-9.fc30.noarch`

**Comment by iranzo** [comment]
Also with virtual env with:

Requirement already up-to-date: feedparser in ./.tox/stampy/lib/python3.7/site-packages (5.2.1)

**Comment by iranzo** [comment]
With python2 version:

~~~
python3-feedparser-5.2.1-9.fc30.noarch
python2-feedparser-5.2.1-9.fc30.noarch
~~~

It doesn't traceback

**Comment by sthen** [comment]
It's fixed with https://github.com/kurtmckee/feedparser/pull/131 but this hasn't made it into a release yet. The following patch against 5.2.1 seems to do the trick:

```
Index: feedparser/feedparser.py
--- feedparser/feedparser.py.orig
+++ feedparser/feedparser.py
@@ -3764,10 +3764,13 @@ def _gen_georss_coords(value, swap=True, dims=2):
     latlons = itertools.imap(float, value.strip().replace(',', ' ').split())
     nxt = latlons.next
     while True:
-        t = [nxt(), nxt()][::swap and -1 or 1]
-        if dims == 3:
-            t.append(nxt())
-        yield tuple(t)
+        try:
+            t = [nxt(), nxt()][::swap and -1 or 1]
+            if dims == 3:
+                t.append(nxt())
+            yield tuple(t)
+        except StopIteration:
+            return
 
 def _parse_georss_point(value, swap=True, dims=2):
     # A point contains a single latitude-longitude pair, separated by
```

**Comment by iranzo** [comment]
It would be great to get a release containing the fix, have found it so far with blogger rss feed, but to be honest... it should not traceback as it does :'(

**Comment by iranzo** [comment]
It works fine, I've just tested it

**Comment by ChanceDurr** [comment]
After editing the _gen_georss_coords with the code above I am still getting the same error as OP. Anything new on this?

**Comment by ChanceDurr** [comment]
Added `from __future__ import generator_stop` to the georss.py and it fixed it

**Comment by kurtmckee** [comment]
@ChanceDurr, thanks for your PR. I've merged it and it will be in the next release of feedparser.

**Comment by AnselmC** [comment]
Hi, first of all, thanks for feed parser :)

However, I'm still seeing this issue both on macOS 10.14.6 and ubuntu 18.04 using python 3.8 and python 3.7 with installation through pypi.
`feedparser.__version__` gives me `5.2.1` and `feedparser` is located in `<module 'feedparser' from '/Users/anselm/miniconda3/envs/msrx/lib/python3.8/site-packages/feedparser.py'>`.
In `feedparser.py::gen_geors_coords` `StopIteration` isn't caught.
Any ideas why I'm still seeing this?
